services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sa-dev-db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    command: sh -c "mix ecto.setup && mix phx.server"
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db-data: